"""empty message

Revision ID: 359acd1fab8a
Revises: 735640feab4d
Create Date: 2022-08-15 11:19:23.038835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359acd1fab8a'
down_revision = '735640feab4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
