"""empty message

Revision ID: 664c7bb321cd
Revises: 359acd1fab8a
Create Date: 2022-08-16 18:02:07.232648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664c7bb321cd'
down_revision = '359acd1fab8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
