"""empty message

Revision ID: 735640feab4d
Revises: 23a45269b7bd
Create Date: 2022-08-12 09:32:25.871339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735640feab4d'
down_revision = '23a45269b7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
